export const assessmentProduct = {
  name: "Platform Readiness Assessment",
  price: "€2,500",
  duration: "3–5 days",
  hero: {
    eyebrow: "Platform Readiness Assessment",
    headline: "A €2,500 decision, not a €2,500 report.",
    sub: "Before you commit serious engineering capacity to a platform transformation, establish what is actually wrong, what it is costing you, what your options are, and whether PlatformBox is the right answer.",
  },
  independence: "The Assessment can — and sometimes should — conclude that you should not buy PlatformBox. It can recommend remediation first, building internally, a hybrid approach, or doing nothing.",
  questions: [
    { title: "Risk", text: "What materially threatens delivery, security, reliability, cost, or scale?" },
    { title: "Money", text: "Where are engineering or cloud resources being consumed, and what opportunity can the evidence support?" },
    { title: "Velocity", text: "Where does the path from code to production create measurable friction, waiting, or toil?" },
    { title: "Strategy", text: "Should you build internally, adopt a platform, use a hybrid approach, or do nothing?" },
    { title: "Fit", text: "Is PlatformBox a strong fit, a conditional fit, not yet, a low fit, or the wrong answer?" },
  ],
  deliverables: [
    "Executive Decision Brief",
    "Current-state and primary-constraint analysis",
    "Prioritized material risk register",
    "Engineering friction and delivery-flow analysis",
    "Cloud and engineering economics analysis where evidence permits",
    "Build vs PlatformBox vs hybrid vs do-nothing comparison",
    "Explicit PlatformBox fit decision",
    "Recommended target state and operating model",
    "90-day action plan with owners and success criteria",
    "Architecture decision records where applicable",
    "Evidence and traceability register",
    "Assumptions, confidence, and customer acceptance record",
  ],
  noSale: [
    "A clearer view of the actual constraint",
    "A prioritized list of material risks and opportunities",
    "A defensible basis for build-vs-buy decisions",
    "A roadmap your engineering organization can execute",
    "A documented record of assumptions and decisions",
    "A basis for saying no to unnecessary platform work",
  ],
  evidence: [
    "Architecture and infrastructure",
    "Terraform and Kubernetes configuration",
    "CI/CD and deployment workflow",
    "Cloud and cost evidence where available",
    "Security and access controls",
    "Operational documentation and telemetry",
    "Engineering workflow and stakeholder input",
  ],
  process: [
    { title: "Discovery", text: "Establish the business context, current constraints, objectives, and evidence needed." },
    { title: "Evidence", text: "Review the relevant technical and operational evidence rather than relying on assumptions." },
    { title: "Analysis", text: "Connect risks, cost, delivery friction, architecture, and strategic options." },
    { title: "Recommendation", text: "Make an explicit recommendation, including alternatives and what not to do." },
    { title: "Decision Brief", text: "Leave with an executive decision view, technical detail, evidence, and an executable next step." },
  ],
  faqs: [
    { q: "Why can't our senior engineers do this?", a: "They can. The question is opportunity cost. The Assessment packages the diagnosis into a decision process so your senior engineers can challenge the conclusions without spending weeks assembling the decision themselves." },
    { q: "Is this just a €2,500 lead-generation exercise for a €20k implementation?", a: "No. The Assessment is designed to remain useful if you never buy PlatformBox. Its recommendation can explicitly be to remediate first, build internally, use another approach, or do nothing." },
    { q: "What if there is not enough data to quantify savings?", a: "The Assessment does not invent precision. Evidence is labelled as measured, estimated, assumed, or unknown, with confidence and a validation path." },
    { q: "What happens if PlatformBox is not a fit?", a: "That is a valid outcome. The purpose is to improve the decision, not to force an implementation." },
    { q: "Does the Assessment expose your internal diagnostic checklist?", a: "No. You receive the conclusions, evidence, reasoning, decisions, and roadmap relevant to your organization. Customer-specific fit constraints and internal diagnostic detail are part of the paid engagement, not a public checklist." },
    { q: "Is the €2,500 credited toward implementation?", a: "Yes. The current commercial model credits the €2,500 Assessment toward PlatformBox Launch if you proceed." },
  ],
} as const;
