"use client";

import { IDP_REPO_URL } from "@/lib/constants";
import Image from "next/image";

// Pre-rendered PNGs generated by:
//   npm run generate-diagrams
// Rendered from architecture.md via Puppeteer + mermaid, then
// optimized with sharp. SVG sources are kept alongside for archiving.
const DIAGRAMS = [
  { src: "/diagrams/golden-path.png", width: 1400, height: 274, label: "Golden Path — Developer Flow" },
  { src: "/diagrams/platform-infra.png", width: 1400, height: 428, label: "Platform Infrastructure" },
  { src: "/diagrams/security-auth.png", width: 1268, height: 974, label: "Security & Auth Flow" },
];

export function LiveArchitectureDiagrams() {
  return (
    <div className="space-y-8">
      {DIAGRAMS.map((img) => (
        <DiagramCard key={img.src} title={img.label} img={img} />
      ))}
      <p className="text-center text-xs text-zinc-600">
        Source:{" "}
        <a
          href={`${IDP_REPO_URL}/-/blob/main/docs/architecture/architecture.md`}
          target="_blank"
          rel="noopener noreferrer"
          className="text-accent hover:text-accent-hover"
        >
          architecture.md
        </a>{" "}
        — generated at build time. If the diagrams look stale, run{" "}
        <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-400">
          npm run generate-diagrams
        </code>
        .
      </p>
    </div>
  );
}

function DiagramCard({ title, img }: { title: string; img: { src: string; width: number; height: number } }) {
  return (
    <div className="rounded-xl border border-white/10 p-2 sm:p-4">
      <p className="mb-2 px-2 text-sm font-semibold text-white sm:px-3">{title}</p>
      <div className="overflow-x-auto rounded-lg bg-zinc-950 p-2">
        <Image
          src={img.src}
          alt={title}
          width={img.width}
          height={img.height}
          className="h-auto w-full max-w-none"
          unoptimized
        />
      </div>
    </div>
  );
}
