"use client";

import { IDP_REPO_URL } from "@/lib/constants";
import Image from "next/image";

// Pre-rendered SVGs generated by:
//   npm run generate-diagrams
// which fetches architecture.md from GitLab and renders each mermaid
// block through a headless browser at build time. No client-side
// mermaid bundle or network fetch is needed in production.
const STATIC_SVGS = [
  { src: "/diagrams/golden-path.svg", width: 2400, height: 800 },
  { src: "/diagrams/platform-infra.svg", width: 2400, height: 900 },
  { src: "/diagrams/security-auth.svg", width: 2400, height: 800 },
];

const DIAGRAM_TITLES = ["Golden Path — Developer Flow", "Platform Infrastructure", "Security & Auth Flow"];

export function LiveArchitectureDiagrams() {
  return (
    <div className="space-y-8">
      {STATIC_SVGS.map((img, i) => (
        <DiagramCard key={img.src} title={DIAGRAM_TITLES[i] ?? `Diagram ${i + 1}`} img={img} />
      ))}
      <p className="text-center text-xs text-zinc-600">
        Source:{" "}
        <a
          href={`${IDP_REPO_URL}/-/blob/main/docs/architecture/architecture.md`}
          target="_blank"
          rel="noopener noreferrer"
          className="text-accent hover:text-accent-hover"
        >
          architecture.md
        </a>{" "}
        — generated at build time. If the diagrams look stale, run{" "}
        <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-400">
          npm run generate-diagrams
        </code>
        .
      </p>
    </div>
  );
}

function DiagramCard({ title, img }: { title: string; img: { src: string; width: number; height: number } }) {
  return (
    <div className="rounded-xl border border-white/10 p-2 sm:p-4">
      <p className="mb-2 px-2 text-sm font-semibold text-white sm:px-3">{title}</p>
      <div className="overflow-x-auto rounded-lg bg-zinc-950">
        <Image
          src={img.src}
          alt={title}
          width={img.width}
          height={img.height}
          className="h-auto w-full"
          unoptimized
        />
      </div>
    </div>
  );
}
